---
name: Lint
on:
  merge_group:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd # v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run flake pre-commit hooks
        run: nix develop -c pre-commit run --all-files
